Assignment 1


In [2]:
import numpy as np

In [3]:
#Q1:Reverse the numpy array
arr=np.array([1,2,3,4,5,6])
print(arr)
print(np.flip(arr))

[1 2 3 4 5 6]
[6 5 4 3 2 1]


In [4]:
#Q2: Flatten the numpy array
arr_1=np.array([[1,2,3],[2,3,4],[1,2,5]])
print(arr_1)
print("Flatten Array By Default", arr_1.flatten())  # By default it is 'C' means the row major order
print("Flatten Array By Value F", arr_1.flatten('F')) #here F tells to   flatten the array by the column major order 
print("Flatten Array By Reshape Function", arr_1.reshape(-1)) #this reshapes the numpy array  by default it is in row major order
print("Flatten Array By Reshape Function", arr_1.reshape(-1, order='F')) #this reshapes in the column major order

[[1 2 3]
 [2 3 4]
 [1 2 5]]
Flatten Array By Default [1 2 3 2 3 4 1 2 5]
Flatten Array By Value F [1 2 1 2 3 2 3 4 5]
Flatten Array By Reshape Function [1 2 3 2 3 4 1 2 5]
Flatten Array By Reshape Function [1 2 1 2 3 2 3 4 5]


In [5]:
#Q3: to compare the array 
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print(np.array_equal(arr1, arr2))  #here np.array_equal is used for comparing the array 



True


In [6]:
#Q4:find the most frequent value and their indices  in the following array 
#counting sort also do the same function as bincount

x = np.array([1,2,3,4,5,1,2,1,1,1])  
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
x1=np.bincount(x).argmax() #this bincount tells the number of each digit in this and the argmax stores the maximum of this
y1=np.bincount(y).argmax()
print('The most frequent array in x is',x1)
print('The most frequent array in y is',y1)
print('This is the output with the indices in this:')
for i in range(len(x)):
    if(x[i]==x1):
        print(i)
    
#This is the output for the Y ARRAY
print("Most frequent value in Array Y is", y1)
print("With Indices:")
for i in range(len(y)):
    if(x[i]==x1):
        print(i)
    



The most frequent array in x is 1
The most frequent array in y is 1
This is the output with the indices in this:
0
5
7
8
9
Most frequent value in Array Y is 1
With Indices:
0
5
7
8
9


In [7]:
#Another question of the above part without the argmax()
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
x1=np.bincount(x)
print(x1)

[0 5 2 1 1 1]


In [8]:
#Q5: Different sum operation
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
#This is for the sum of all the elements
print('Sum of all the elements:',np.sum(gfg))
#This is for the sum of all the elemets row wise.
print('Sum of all the elements Row Wise:',np.sum(gfg,axis=1)) #here axis=1 helps in summing the values row wise
#This is for the sum of all the elements column wise.
print('Sum of all the elements Row Wise:',np.sum(gfg,axis=0)) #here axis=0 helps in summing the values column wise

Sum of all the elements: 45
Sum of all the elements Row Wise: [[14]
 [16]
 [15]]
Sum of all the elements Row Wise: [[20  9 16]]


In [9]:
#Q6: Different mathematical operations:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
#sum of diagonal
print("Sum of diagonal elements:", np.trace(n_array)) #np.trance is used to find the sum of the diagonal elements
eigenvalues, eigenvectors = np.linalg.eig(n_array) #this stores the eigenvalue and vector  for this array given above.
#Eigen value of this: 
print("Eigenvalues:", eigenvalues)
#Eigen vector of this:
print("Eigenvectors:", eigenvectors)
#Inverse of this matrix
print("Inverse of a matrix:", np.linalg.inv(n_array))
#Determinant of this matrix
print("Determinant of matrix:", np.linalg.det(n_array))







Sum of diagonal elements: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors: [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of a matrix: [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix: 137180.0000000001


In [10]:
#Q7: Doing multiplication and finding the covariance of the following matrix
#i:
print('This is the solution for the first one:')
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
print("Multiplication:")
print(np.multiply(p, q)) #np.multiply is used
print("Covariance:")
print(np.cov(p, q))  #np.cov is used
#ii:
print('This is the function for second one:')
p1 = np.array([[1, 2], [2, 3], [4, 5]])
q1= np.array([[4, 5, 1], [6, 7, 2]])
print("Multiplication:")
print(np.multiply(p1, q1.T))
print("Covariance:")
print(np.cov(p1, q1))



This is the solution for the first one:
Multiplication:
[[ 4 10]
 [12 21]]
Covariance:
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
This is the function for second one:
Multiplication:
[[ 4 12]
 [10 21]
 [ 4 10]]
Covariance:


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3